<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='https://cdn.jsdelivr.net/foundation/6.2.4-rc2/foundation.min.css' rel='stylesheet' type='text/css'> 
		<script src='https://cdn.jsdelivr.net/foundation/6.2.4-rc2/foundation.min.js'></script>       
    <!--style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style-->
    </head>
    <body>
		<div class="top-bar">
		  <div class="top-bar-title">
			<span data-responsive-toggle="responsive-menu" data-hide-for="medium">
			  <button class="menu-icon dark" type="button" data-toggle></button>
			</span>
			<strong>Site Title</strong>
		  </div>
		  <div id="responsive-menu">
			<div class="top-bar-left">
			  <ul class="dropdown menu" data-dropdown-menu>
				<li><a href="#">One</a></li>
				<li><a href="#">Two</a></li>
				<li><a href="#">Three</a></li>
			  </ul>
			</div>
			<div class="top-bar-right">
			  <ul class="menu">
				<li><input type="search" placeholder="Search"></li>
				<li><button type="button" class="button">Search</button></li>
			  </ul>
			</div>
		  </div>
		</div>
        <h1>Slim</h1>

        <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>
    </body>
</html>
